doc ///
   Key 
      MatroidComplexes
   Headline 
      Tools for computing the matroid chain complex
   Description
    Text
      The matroid complex generalizes Kontsevich's graph complex to matroids; see {\it Tatiana V. Alekseyevskaya, Alexandre V. Borovik: /. M. Gelfand, and Neil White, Matroid Homology (2000)}. 

      This package extends the Matroids package to compute the terms in the subcomplex generated by matroids of fixed rank $r$ in degree $\leq 9$, which can be used to form the entire complex.

      Rational coefficients are assumed: the matroid complex is generated by isomorphism classes of matroids which do not admit automorphisms acting as an odd permutation on the groundset. Elements with odd automorphisms have 2-torsion, and thus do not contribute to the ratinoal vector spaces.      

///


doc ///
   Key 
    withoutOddAut
    (withoutOddAut,Matroid)
   Headline
    Determines if a matroid admits an odd automorphism
   Usage
    withoutOddAut(M)
   Inputs
    M: Matroid
   Outputs
    : Boolean
   Description
    Text
      Calls getIsos(M,M) from the Matroids package and checks if there are no automorphisms which act as an odd permutation on the ground set. Ground set elements are labeled 
      $\{0,1,2,\dots,n-1\}$ as in the Matroids package. Returns true if no odd automorphisms exist, and false otherwise.
      
      Matroids which admit odd automorphisms vanish in the rational matroid complex. In the 
      example below, we ask whether the uniform matroids $U_{2,4}$ admits odd automorphisms. 
      That is, a matroid automorphism given by an odd permutation of its ground set $\{0,1,2,3\}.$
    Example
      M = uniformMatroid(2,4);
      withoutOddAut(M)

///

doc ///
   Key 
    rankedBasis
    (rankedBasis,Number,Number)
   Headline
    A list containing the basis elements of $C^r_n$
   Usage
    rankedBasis(n,r)
   Inputs
    n: Number
    r: Number
   Outputs
    : List
   Description
    Text
      Given a pair $(n,r)$, $0\leq r\leq n\leq n,$ this method returns a list of rank $r$ 
      matroids on $n$ ground set elements which do not admit odd automorphisms. These matroids
      constitute the basis of $C^r_n$, the subspace in the matroid complex generated by matroids of rank $r$ on $n$ elements .

      In example below, we generate the basis of rank $3$ matroids on $6$ ground set elements. 
    Example
      rankedBasis(6,3)
     
///

doc ///
   Key 
    diffMatrixColumn
    (diffMatrixColumn,Matroid,List)
   Headline
    the column vector which is the image of a basis under the deletion differential with respect to standard bases
   Usage
    diffMatrixColumn(M,T)
   Inputs
    M: Matroid
    T: List
   Outputs
    : List
   Description
    Text
      Given a matroid representing a basis element of (a subspace of) C_n, return the corresponding column vector of the
      matrix representing the deletion differential from C_n to C_{n-1}
      with respect to the standard bases on Q^{dim C_n} and
      Q^{dim C_{n-1}}.
      
      In example below, we begin by defining the cyclic matroid $M$ associated to the wheel graph $W_3$ (with three spokes), 
      which is a element of the basis of $C^3_6,$ as can be verified by generating rankedBasis(6,3). Then, we generate the 
      column vector associated to $M$ under the deletion differential from $C_6$ to $C_5$, with respect to the standard bases 
      on $Q^{dim C_n}$ and $Q^{dim C_{n-1}}$.
    Example
      M = wheel 3;
      targetBasis = rankedBasis(6,3);
      diffMatrixColumn(M,targetBasis)
  
///

doc ///
   Key 
    diffMatrix
    (diffMatrix,List,List)
   Headline
    the matrix representing the deletion differential with respect to standard bases
   Usage
    diffMatrix(S,T)
   Inputs
    S: List
    T: List
   Outputs
    : Matrix
   Description
    Text
      Given the pair of bases for a subspace $V$ of $C_n$ and a basis for a subspace $W$
      of $C_{n-1}$ containing the image of $V$ under the deletion differential, return the 
      matrix representing the standard bases on $QQ^{dim V}$ and $QQ^{dim W}$, respectively. 
      The first element of the first list will correspond to the basis vector 
      $e_1 = (1,0,...,0)^T$, etc.
 
      In the following example, we generate the matrix associated to the deletion differential 
      from $C^3_7$ to $C^3_6$ with respect to the standard bases $QQ^9$ and $QQ^2,$ the dimensions
      of which we verified by running rankedBasis(7,3) and rankedBasis(6,3), respectively. 
    Example
      sourceBasis = rankedBasis(7,3);
      targetBasis = rankedBasis(6,3);
      diffMatrix(sourceBasis,targetBasis)
///
